### ISSUE TITLE
Age Chart in ACS 2015 Charts Tab has change in the number of categories.

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-DemographicRegional#47]
![pic1](https://user-images.githubusercontent.com/5183539/27656442-cedc6106-5bfd-11e7-95ab-981874886abb.PNG)
![pic2](https://user-images.githubusercontent.com/5183539/27656444-d06c73f8-5bfd-11e7-8782-ec777adf279b.PNG)

**Comment by Jfairfield1** [comment]
No longer supporting the regional viewer.
