### ISSUE TITLE
Custom Summary - ACS Block Groups Tab switch zoom to link from Tract to Block Group

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-DemographicRegional#48]
![capture](https://user-images.githubusercontent.com/5183539/29097026-88ee7476-7c4c-11e7-8d69-87ccc0b0ef1d.PNG)

When zooming to block group do not clear graphics and redraw.  Level full selection

**Comment by Jfairfield1** [comment]
No longer supporting the regional viewer.
